name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build pwsh.exe
        run: |
          sudo apt-get install -y g++-mingw-w64-x86-64
          x86_64-w64-mingw32-g++ -O3 -DNDEBUG -std=c++2b -static -s -o pwsh.exe pwsh.cpp

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Bump npm version
        run: |
          CURRENT_VERSION=$(curl -s https://registry.npmjs.org/pwsh-copilot/latest | jq -r '.version' 2>/dev/null || echo "0.0.0")
          echo "Current published version: $CURRENT_VERSION"
          npm version $CURRENT_VERSION --no-git-tag-version --allow-same-version
          npm version patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "New version: $NEW_VERSION"

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public