name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build pwsh.exe
        run: |
          cl /O2 /GL /Gy /DNDEBUG /std:c++latest pwsh.cpp /link /RELEASE

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Bump npm version
        run: |
          $CURRENT_VERSION = (Invoke-RestMethod -Uri 'https://registry.npmjs.org/pwsh-copilot/latest' -ErrorAction SilentlyContinue).version
          if (-not $CURRENT_VERSION) { $CURRENT_VERSION = "0.0.0" }
          npm version $CURRENT_VERSION --no-git-tag-version --allow-same-version
          npm version patch --no-git-tag-version

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public