name: Node.js Package

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  publish-npm:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build pwsh.exe
        run: |
          dotnet publish pwsh.cs
          move artifacts/pwsh/pwsh.exe pwsh.exe

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Bump npm version
        run: |
          $CURRENT_VERSION = (Invoke-RestMethod -Uri 'https://registry.npmjs.org/pwsh-copilot/latest' -ErrorAction SilentlyContinue).version
          if (-not $CURRENT_VERSION) { $CURRENT_VERSION = "0.0.0" }
          Write-Host "Current published version: $CURRENT_VERSION"
          npm version $CURRENT_VERSION --no-git-tag-version --allow-same-version
          npm version patch --no-git-tag-version
          $NEW_VERSION = (Get-Content package.json | ConvertFrom-Json).version
          Write-Host "New version: $NEW_VERSION"

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
