name: release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: meta
        shell: bash
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish self-contained exe
        run: |
          dotnet publish .\src\pwsh-copilot.csproj `
            -c Release `
            -r win-x64 `
            -p:PublishSingleFile=true `
            -p:SelfContained=true `
            -p:EnableCompressionInSingleFile=true `
            -p:DebugType=none `
            -o out

      - name: Place built exe in package bin
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path .\bin\win-x64 | Out-Null
          Copy-Item .\out\pwsh-copilot.exe .\bin\win-x64\pwsh.exe

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Set npm version from tag (no git tag write)
        run: npm version ${{ steps.meta.outputs.version }} --no-git-tag-version

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
